language: python
sudo: false
python:
  - "3.4"
cache:
  - directories:
    - ~/.cache/pip
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
install:
  - psql -c 'CREATE DATABASE qanda' -U postgres
  - pip install pip wheel setuptools -U
  - pip install -r requirements.txt
script:
  - make test
notifications:
  email: false
